### PR TITLE
Added pooling to AsyncKeyedLock to reduce memory allocations

### PR DESCRIPTION
**Pull request by MarkCiliaVincenti**

### CODE REVIEW

**Comment by MarkCiliaVincenti** [comment]
Sorry @vladimir-litvinchik had forgotten to enable pooling

**Comment by vladimir-litvinchik** [comment]
@MarkCiliaVincenti 

Not an issue. Thank you for your pull requests.

**Comment by MarkCiliaVincenti** [comment]
> @MarkCiliaVincenti
> 
> Not an issue. Thank you for your pull requests.

You're welcome!

**Comment by MarkCiliaVincenti** [comment]
Looking forward to seeing it go to a new release version :)

**Comment by vladimir-litvinchik** [comment]
@MarkCiliaVincenti 

The release is planned for the end of the week.

**Pull request merged**
