### PR TITLE
Switched from AsyncDuplicateLock to AsyncKeyedLock

### PR DESCRIPTION
**Pull request by MarkCiliaVincenti**
Switched from AsyncDuplicateLock to AsyncKeyedLock, which provides better performance and lower memory usage.

### CODE REVIEW

**Comment by MarkCiliaVincenti** [comment]
@vladimir-litvinchik

**Comment by MarkCiliaVincenti** [comment]
@mikhail-evgrafov

**Comment by vladimir-litvinchik** [comment]
@MarkCiliaVincenti 

I'm sorry for the delayed response. Thank you for your efforts. Can you please share in which way you've improved the solution Stephen Cleary proposed in his answer on SO?

**Comment by MarkCiliaVincenti** [comment]
> @MarkCiliaVincenti
> 
> I'm sorry for the delayed response. Thank you for your efforts. Can you please share in which way you've improved the solution Stephen Cleary proposed in his answer on SO?

Hi,

So I had started off with Cleary's solution and made several iterations to improve it, benchmarking every time. So it uses an underlying concurrent dictionary which makes it more scalable and performant, it makes much fewer memory allocations, is much faster in benchmarks and provides more features like timeouts, cancellation tokens, the ability to define the max concurrent count for a lock (ie not necessarily 1), generics instead of object and optional pooling to further reduce allocations.

**Comment by MarkCiliaVincenti** [comment]
Ready with changes @vladimir-litvinchik

**Comment by MarkCiliaVincenti** [comment]
@vladimir-litvinchik

**Comment by MarkCiliaVincenti** [comment]
@vladimir-litvinchik @saqibmasood @sabir-aspose @shahzad-latif

**Comment by MarkCiliaVincenti** [comment]
@vladimir-litvinchik any thoughts on this please?

**Comment by MarkCiliaVincenti** [comment]
@vladimir-litvinchik are you interested in this PR please, or shall I close it?

**Comment by vladimir-litvinchik** [comment]
@MarkCiliaVincenti 

I believe that you are one of the most patient people that I know.  I will gladly accept your pull request.

**Comment by MarkCiliaVincenti** [comment]
> @MarkCiliaVincenti
> 
> I believe that you are one of the most patient people that I know. I will gladly accept your pull request.

Hahahahahaha

So in Gmail I got the preview and it showed me up to "I believe that you are one of the most pa"

I opened the email fully expecting something bad... I was dreading "pathetic" :) So reading it in full was a relief.

Cheers!

**Comment by MarkCiliaVincenti** [comment]
Gentle nudge 😜

**Comment by MarkCiliaVincenti** [comment]
Gentle nudge @vladimir-litvinchik 😜

**Pull request merged**
